{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}"
  namespace: {{ .Release.Namespace | quote }}
  labels:
        {{- include "php.labels" . | nindent 4 }}
data:
{{- toYaml .Values.secret.passwords | nindent 2}}
{{- end -}}