apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel-nginx.fullname" . }}
  namespace: default
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=production
    APP_KEY=base64:rV6CWVRRS7NGrEpsKrHW6UpzzeOhtbtGMI82wy1k3+o=
    APP_DEBUG=false

    LOG_CHANNEL=stack

    DB_CONNECTION=pgsql
    DB_HOST=dd451baf-6258-4307-b21d-b9bf8f0ab834.bn2a0fgd0tu045vmv2i0.databases.appdomain.cloud
    DB_PORT=30600
    DB_DATABASE=ibmclouddb
    DB_USERNAME=ibm_cloud_c10b1c48_aaf1_41e6_b09c_548cfb86a5ea
    DB_PASSWORD=${PG_PASSWORD}

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    MAIL_MAILER=smtp
    MAIL_HOST=smtp.mailtrap.io
    MAIL_PORT=2525
    MAIL_USERNAME=null
    MAIL_PASSWORD=null
    MAIL_ENCRYPTION=null
    MAIL_FROM_ADDRESS=null
    MAIL_FROM_NAME="${APP_NAME}"

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1

    MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
    MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

