{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "laravel-nginx.serviceAccountName" . }}
  labels:
{{ include "laravel-nginx.labels" . | nindent 4 }}
{{- end -}}
